config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'uploads/index'

  get 'uploads/new'

  get 'uploads/create'

  post 'upload/create'

  get 'uploads/index'

  get 'uploads/show'

  get 'photo/show'

  get 'photo/show'

  get 'items/new'

  get 'items/create'

  post 'items/create'

  get 'items/show'

  get 'items/new'

  resources :uploads
  resources :items
  get 'welcome/index'

  resources :announcements
  resources :documents

  get 'volunteer/index'
  get  'about'   => 'volunteer#about'
  get  'contact' => 'volunteer#contact'

  root 'welcome#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/document.rb
class Document < ActiveRecord::Base
	def initialize(params = {})
  file = params.delete(:file)
  super
  if file
    self.filename = sanitize_filename(file.original_filename)
    self.content_type = file.content_type
    self.file_contents = file.read
  end
end
private
  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	def new
      @announcement = Announcement.new
	end

  def update
  @announcement = Announcement.find(params[:id])
 
  if @announcement.update(announcement_params)
    redirect_to @announcement
  else
    render 'edit'
  end
end

  def edit
      @announcement = Announcement.find(params[:id])
  end

	def index
    	@announcement = Announcement.all
  end

	def show
    	@announcement = Announcement.find(params[:id])
  end

	def create
  		@announcement = Announcement.new(announcement_params)
 
  		if @announcement.save
        redirect_to @announcement
      else
        render 'new'
	end
end
 
	private
  	def announcement_params
    	params.require(:announcement).permit(:title, :text)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    send_data(@document.file_contents,
              type: @document.content_type,
              filename: @document.filename)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # POST /documents
  # POST /documents.json
  def create
    name = params[:document][:file].original_filename
    directory = "app/assets/images/"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:document][:file].read) }
    flash[:notice] = "File uploaded"

    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file)
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
	  name = params[:upload][:file].original_filename
    directory = "public/images/upload"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
    flash[:notice] = "File uploaded"
    
    @upload = Upload.new(upload_params)

    if @upload.save
      redirect_to @upload
    else
      render 'new'
    end
  end

  def index
    @upload = Upload.all
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def upload_params
      params.require(:upload).permit(:name)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
	  name = params[:upload][:file].original_filename
    directory = "public/images/upload/"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
    flash[:notice] = "File uploaded"
    
    @upload = Upload.new(upload_params)

    if @upload.save
      redirect_to @upload
    else
      render 'new'
    end
  end

  def index
    @upload = Upload.all
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def upload_params
      params.require(:upload).permit(:name)
  end
end

app/controllers/volunteer_controller.rb
class VolunteerController < ApplicationController
  def index
  end
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement do |f| %>
 
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@announcement.errors.count, "error") %> prohibited
        this announcement from being saved:
      </h2>
      <ul>
        <% @announcement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "91x10" %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :size => "90x10" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/announcements/edit.html.erb
<%= render 'layouts/vheader' %>
<h1>Editing article</h1>
 <div class="container">
   <div class="row">
     <div class="col-md-12"> 
     <%= render 'form' %>
    </div>
  </div>
</div>
 
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<%= render 'layouts/vheader' %>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New', new_announcement_path %>
      <table class="table">
          <tbody>
            <tr>
              <th>Title</th>
              <th>Text</th>
              <th colspan="2"></th>

         
          <% @announcement.each do |announcement| %>
            </tr>
          
            <tr>
              <td><%= announcement.title %></td>
              <td><%= link_to 'Show', announcement_path(announcement) %></td>
              <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </table>
    </div>
  </div>

</div>

app/views/announcements/new.html.erb
<%= render 'layouts/vheader' %>
<h1>New Announcment</h1>
<div class="container">
  <div class="row">
    <div class="col-md-12"> 
    <%= render 'form' %>
        </div>
      </div>
    </div>
 
<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<%= render 'layouts/vheader' %>
<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @announcement.text %>
</p>
<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/documents/_form.html.erb
<!-- app/views/documents/_form.html.erb -->
<%= form_for(@document) do |f| %>
  <div class="field">
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/index.html.erb
<%= render 'layouts/vheader' %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New Document', new_document_path %>
      <table class="table">
        <thead>
    <tr>
      <th>Image</th>
      <th>Filename</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <% @directory = "public/images/upload/" + document.filename %>
        <td><%= image_tag(document.filename, :size => "80x80", :alt => "Picture", :width => '100', :height => '100') %></td>
        <td><%= document.filename %></td>
        <td><%= button_to 'Download', document, method: :get %></td>
        <td><%= button_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
  <% end %>
        </table>
      </table>
    </div>
  </div>
</div>

<br>

app/views/documents/new.html.erb
<%= render 'layouts/vheader' %>
<h1>New Announcment</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', announcements_path %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/new.html.erb
<%= render 'layouts/vheader' %>
<h3>New item</h3>
<div class="container">
  <div class="row">
      	<%= form_tag( {:action=>'create'}, :multipart=>true ) do %>
      	  <% if flash[:error] %>
      	    <div class="error"><%= flash[:error] %></div>
      	  <% end -%>

      	  <p><label for="item_name">Name</label><br/>
      	  <%= text_field 'item', 'name'  %></p>

      	  <p><label for="item_description">Description</label><br/>
      	  <%= text_area 'item', 'description', :rows => 5  %></p>

      	  <p><label for="photo">Photo</label><br />
      	  <%= file_field("photo", "photo", :class => 'textinput') %>

      	  <%= submit_tag "Create" %>
      	<% end %>
  </div>

</div>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/photo/show.html.erb
<h1>Photo#show</h1>
<p>Find me in app/views/photo/show.html.erb</p>

app/views/upload/create.html.erb
<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
<% end %>
<% form_tag '/upload/create', { :multipart => true } do %>
    <p>
    <%= file_field_tag 'upload[file]' %>
    </p>
    <p>
    	<%= submit_tag "Upload" %>
    </p>
<% end %>

app/views/upload/index.html.erb
<%= render 'layouts/vheader' %>

app/views/upload/new.html.erb
<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
<% end %>
<%= form_tag '/upload/create', { :multipart => true } do %>
    <p>
    <%= file_field_tag 'upload[file]' %>
    </p>
    <p>
    	<%= submit_tag "Upload" %>
    </p>
<% end %>

app/views/upload/show.html.erb
<h1>Upload#show</h1>
<p>Find me in app/views/upload/show.html.erb</p>

app/views/uploads/create.html.erb
<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
<% end %>
<% form_tag '/upload/create', { :multipart => true } do %>
    <p>
    <%= file_field_tag 'upload[file]' %>
    </p>
    <p>
    	<%= submit_tag "Upload" %>
    </p>
<% end %>

app/views/uploads/index.html.erb
<%= render 'layouts/vheader' %>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New', new_uploads_path %>
      <table class="table">
          <tbody>
            <tr>
              <th colspan="2"></th>

         
          <% @upload.each do |upload| %>
            </tr>
          
            <tr>
              <td><%= upload.name %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </table>
    </div>
  </div>

</div>

app/views/uploads/new.html.erb
<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
<% end %>
<%= form_tag '/upload/create', { :multipart => true } do %>
    <p>
    <%= file_field_tag 'upload[file]' %>
    </p>
    <p>
    	<%= submit_tag "Upload" %>
    </p>
<% end %>

app/views/uploads/show.html.erb
<%= render 'layouts/vheader' %>
<p>
  <strong>File Name:</strong>
  <%= @upload.name %>
</p>
 
<p>

</p>
<%= link_to 'Back', new_upload_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/volunteer/about.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'layouts/header' %>

<body>
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>A SafeFurr Place</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag("logo.png", :class => "img-responsive img-left") %>
                </div>
                <div class="col-md-6">
                    <p>We rescue animals from members of the community in need, off the streets and from high kill shelters in the Kern County area. We are a 100% volunteer-ran organization meaning nobody makes a dime besides our animals! We are also a "foster-based" rescue; which means all of our adoptable pets are placed in temporary foster homes until they find their forever homes! One day we dream of having the property to have a bigger facility where we will run our "pack-style" rescue where no animals will be held in kennel runs or cages; they will all live happily balanced lives and will be able to coexist problem-free!</p>
                    <p>Our mission is to rescue, rehabilitate, and re-home animals in need in the area of Kern County; as well as educate our local community about the pet overpopulation problem and assist them in becoming responsible pet owners.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Our
                        <strong>Team</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <%= render 'layouts/footer' %>

    <!-- jQuery -->
    <%= javascript_include_tag "jquery" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min" %>

</body>

</html>

app/views/volunteer/contact.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'layouts/header' %>

<body>
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                    <strong>Contact</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed/v1/place?q=bakersfield&key=AIzaSyAUuYKOp9P6v_clHUZBRqEYVrTy_ToLeYk"></iframe>
                </div>
                <div class="col-md-4">
                    <p>Phone:
                        <strong>661.203.1633</strong>
                    </p>
                    <p>Email:
                        <strong><a href="mailto:name@example.com">info@asafefurrplace.com</a></strong>
                    </p>
                    <%# <p>Address:
                        <strong>No address?
                            <br>Beverly Hills, CA 90210</strong>
                    </p> %>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>form</strong>
                    </h2>
                    <hr>
                    <p>Want to write us? fill out the form below!</p>
                    <form role="form">
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label>Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Email Address</label>
                                <input type="email" class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Phone Number</label>
                                <input type="tel" class="form-control">
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group col-lg-12">
                                <label>Message</label>
                                <textarea class="form-control" rows="6"></textarea>
                            </div>
                            <div class="form-group col-lg-12">
                                <input type="hidden" name="save" value="contact">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <%= render 'layouts/footer' %>

    <!-- jQuery -->
    <%= javascript_include_tag "jquery" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min" %>

</body>

</html>

app/views/volunteer/home.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'layouts/header' %>

<body>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <%= image_tag("slide-1.jpg", :class => "img-responsive img-full") %>
                            </div>
                            <div class="item">
                                <%= image_tag("slide-2.jpg", :class => "img-responsive img-full") %>
                            </div>
                            <div class="item">
                                <%= image_tag("slide-3.jpg", :class => "img-responsive img-full") %>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">A SafeFurr Place</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>
                            <strong>Animal Rescue</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Who 
                        <strong>we are</strong>
                    </h2>
                    <hr>
                    <%= image_tag("logo.png", :class => "img-responsive img-left") %>
                    <hr class="visible-xs">
                    <p>A small non-profit organization with a completed 501c3 staus based in Bakersfiefld, CA (Kern County). Every animal deserves to live in a "SafeFurr" place!</p>
                    <p>Our mission is to rescue, rehabilitate and re-home animals in need in the area of Kern County; as well as educate our local community about the pet overpopulation problem and assist them in becoming responsible pet owners.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">
                        <strong>Donate!</strong>
                    </h2>
                    <hr>
                    <p>To come...</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <%= render 'layouts/footer' %>

    <!-- jQuery -->
    <%= javascript_include_tag "jquery" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min" %>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>
<%= link_to 'Announcements', controller: 'announcements' %> 

app/views/volunteer/index.html.erb
<h1>Volunteer</h1>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html lang="en">

<%= render 'layouts/header' %>

<body>
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>A SafeFurr Place</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <%= image_tag("logo.png", :class => "img-responsive img-left") %>
                </div>
                <div class="col-md-6">
                    <p>We rescue animals from members of the community in need, off the streets and from high kill shelters in the Kern County area. We are a 100% volunteer-ran organization meaning nobody makes a dime besides our animals! We are also a "foster-based" rescue; which means all of our adoptable pets are placed in temporary foster homes until they find their forever homes! One day we dream of having the property to have a bigger facility where we will run our "pack-style" rescue where no animals will be held in kennel runs or cages; they will all live happily balanced lives and will be able to coexist problem-free!</p>
                    <p>Our mission is to rescue, rehabilitate, and re-home animals in need in the area of Kern County; as well as educate our local community about the pet overpopulation problem and assist them in becoming responsible pet owners.</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Our
                        <strong>Team</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <h3>John Smith
                        <small>Job Title</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <%= render 'layouts/footer' %>

    <!-- jQuery -->
    <%= javascript_include_tag "jquery" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min" %>

</body>

</html>