config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'uploads/index'

  get 'uploads/new'

  get 'uploads/create'

  post 'upload/create'

  get 'uploads/index'

  get 'uploads/show'

  get 'photo/show'

  get 'photo/show'

  get 'items/new'

  get 'items/create'

  post 'items/create'

  get 'items/show'

  get 'items/new'

  resources :uploads
  resources :items
  get 'welcome/index'

  resources :announcements
  resources :documents

  get 'volunteer/index'
  get  'about'   => 'volunteer#about'
  get  'contact' => 'volunteer#contact'

  root 'welcome#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/document.rb
class Document < ActiveRecord::Base
	def initialize(params = {})
  file = params.delete(:file)
  super
  if file
    self.filename = sanitize_filename(file.original_filename)
    self.content_type = file.content_type
    self.file_contents = file.read
  end
end
private
  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    send_data(@document.file_contents,
              type: @document.content_type,
              filename: @document.filename)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # POST /documents
  # POST /documents.json
  def create
    name = params[:document][:file].original_filename
    directory = "app/assets/images/"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:document][:file].read) }
    flash[:notice] = "File uploaded"

    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file)
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
	  name = params[:upload][:file].original_filename
    directory = "public/images/upload"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
    flash[:notice] = "File uploaded"
    
    @upload = Upload.new(upload_params)

    if @upload.save
      redirect_to @upload
    else
      render 'new'
    end
  end

  def index
    @upload = Upload.all
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def upload_params
      params.require(:upload).permit(:name)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
	  name = params[:upload][:file].original_filename
    directory = "public/images/upload/"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
    flash[:notice] = "File uploaded"
    
    @upload = Upload.new(upload_params)

    if @upload.save
      redirect_to @upload
    else
      render 'new'
    end
  end

  def index
    @upload = Upload.all
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def upload_params
      params.require(:upload).permit(:name)
  end
end

app/controllers/volunteer_controller.rb
class VolunteerController < ApplicationController
  def index
  end
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                
                <p><%= link_to(image_tag("facebook.png", :class => "img-center"), "https://www.facebook.com/ASafeFurrPlace/timeline") %><br>
                Copyright &copy; A SafeFurr Place 2016</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>A SafeFurr Place Animal Rescue</title>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "bootstrap.min" %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag "SafeFurrPlace" %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<header>
	<%#<div class="brand">A SafeFurr Place</div>
    <div class="address-bar">Animal Rescue</div> %>
    
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">A SafeFurr Place</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
                    <li>
                        <%= link_to "About", about_path %>
                    </li>
                    <%# <li>
                        To come....
                        <a href="blog.html">Blog</a>
                    </li> %>
                    <li>
                        <%= link_to "Contact", contact_path %>
                    </li>
                    <li>
                        <%= link_to "Adoptable Pets", documents_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
</header>

app/views/layouts/_vheader.html.erb
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>A SafeFurr Place Animal Rescue</title>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "bootstrap.min" %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag "SafeFurrPlace" %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<header>
	<%#<div class="brand">A SafeFurr Place</div>
    <div class="address-bar">Animal Rescue</div> %>
    
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">A SafeFurr Place</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
                    <li>
                        <%= link_to "Announcements", announcements_path %>
                    </li>
                    <%# <li>
                        To come....
                        <a href="blog.html">Blog</a>
                    </li> %>
                    <li>
                        <%= link_to "Pet Database", documents_path %>
                    </li>
                    <li>
                        <%= link_to "Donations", contact_path %>
                    </li>
                    <li>
                        <%= link_to "Sign Out", contact_path %>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SafeFurrPlace</title>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>